language: erlang
otp_release:
  - R15B03
  - R16B03-1
  - 17.4
  - 18.2
  - 19.1
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install postgresql-9.4-postgis-2.1 postgresql-contrib-9.4
addons:
  postgresql: "9.4"
script:
  - sudo chmod 777 /var/run/postgresql/
  - ./setup_test_db.sh
  - ./start_test_db.sh &
  - sleep 1
  - make create_testdbs
  - make test

